#!/bin/sh        
#PBS -N serial
### Declare job non-rerunable
#PBS -r n
### Output files
#PBS -e serial.err.$PBS_JOBID
#PBS -o serial.log.$PBS_JOBID
### Mail to user
#PBS -m abe -M h@gmail.com
### Queue name
#PBS -q long 
### Number of nodes
#PBS -l nodes=anode4:ppn=20
#PBS -l mem=300M
#PBS -l walltime=1000:00:00

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`

# Run the serial Program  "a.out"
./N1_norm run.mac
exit 0

